first assignment
rishikesh-dhanawade-emtec/jitendra_repo pull request #1
Opened 2022-08-25 03:29 UTC by jeet1331999

This is my first assignment of SQL

2022-08-25 06:05 UTC, rishikesh-dhanawade-emtec commented on SQL Assignment 1.txt
> +--	FOREIGN KEY(id) references school(id)
Column name missing

2022-08-25 06:06 UTC, rishikesh-dhanawade-emtec commented on SQL Assignment 1.txt
> +--add some dummy data
Where are insert statements to add dummy data?

2022-08-25 06:08 UTC, jeet1331999 commented
Sorry sir i forgot to add dummy data

From: rishikesh-dhanawade-emtec ***@***.***>
Sent: Thursday, August 25, 2022 11:36 AM
To: rishikesh-dhanawade-emtec/jitendra_repo ***@***.***>
Cc: Patil, Jitendra ***@***.***>; Author ***@***.***>
Subject: Re: [rishikesh-dhanawade-emtec/jitendra_repo] first assignment (PR #1)

CAUTION External EMail.

@rishikesh-dhanawade-emtec commented on this pull request.

________________________________

In SQL Assignment 1.txt<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frishikesh-dhanawade-emtec%2Fjitendra_repo%2Fpull%2F1%23discussion_r954535301&data=05%7C01%7CJitendra.Patil%40emtecinc.com%7C007c71471c74430068d508da865feed5%7Cbcdadde49fc242009d1dc1efe1c77b43%7C0%7C0%7C637970043852857550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k0UmL34mFFpZH6yvZ%2B0pSRfjEZcunplLH9A2g%2Bvo8FQ%3D&reserved=0>:

> @@ -0,0 +1,30 @@

+              ---Assigment 1---

+--create 'student_db' database

+--create following tables in database with proper data types

+--student: id (PK), name, address, phone, email, age, schoolId (FK)

+--school: id (PK), name, address, principal, phone

+--create relationship as shown in the table schema

+--add some dummy data

Where are insert statements to add dummy data?

-
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frishikesh-dhanawade-emtec%2Fjitendra_repo%2Fpull%2F1%23pullrequestreview-1084830886&data=05%7C01%7CJitendra.Patil%40emtecinc.com%7C007c71471c74430068d508da865feed5%7Cbcdadde49fc242009d1dc1efe1c77b43%7C0%7C0%7C637970043852857550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xPzLVrgl2FAvB3bAa6EdQAgXPHAuGg%2BOTc8glkFVZy8%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2USP7OD2FUYBE4WUHQMDUTV24ENZANCNFSM57RPXFHQ&data=05%7C01%7CJitendra.Patil%40emtecinc.com%7C007c71471c74430068d508da865feed5%7Cbcdadde49fc242009d1dc1efe1c77b43%7C0%7C0%7C637970043852857550%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b7%2BE4SLO0BcUUg6aQy5LxmCn0dXPTAR%2FirU6oW1%2Fqus%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-08-25 06:09 UTC, rishikesh-dhanawade-emtec requested changes
resolve the comments and submit it again

2022-08-25 06:09 UTC, jeet1331999 commented on SQL Assignment 1.txt
> +--	FOREIGN KEY(id) references school(id)
Sorry sir , I forgot to add column name

> Column name missing

2022-08-25 06:11 UTC, jeet1331999 commented
> resolve the comments and submit it again

ok sir

2022-09-08 05:51 UTC, rishikesh-dhanawade-emtec approved these changes
approved

2022-09-13 10:18 UTC, merged